
import { Injectable } from '@angular/core';
import { Entity, SectorId } from '../../models/game.models';

interface EntitySnapshot {
    type: string;
    subType?: string;
    x: number; y: number; z: number;
    hp: number;
    state: string;
    equipment?: any; // Only save equipped items
    factionId?: string;
}

interface FloorState { entities: EntitySnapshot[]; visited: boolean; timestamp: number; }

@Injectable({ providedIn: 'root' })
export class WorldStateService {
  private sectors = new Map<SectorId, FloorState>();

  hasSector(id: SectorId): boolean { return !!this.sectors.get(id); }

  saveSector(id: SectorId, entities: Entity[]) {
      const snapshot: EntitySnapshot[] = entities
        .filter(e => {
            // Filter out transient entities
            if (e.type === 'HITBOX' || e.type === 'DECORATION' || (e.type === 'DESTRUCTIBLE' && e.hp <= 0)) return false;
            
            // Filter out WALLs because they are usually loaded from Zone Templates or regenerated by WorldGenerator
            if (e.type === 'WALL') return false;

            // CRITICAL: Do NOT save NPCs in the HUB. They are structural fixtures loaded from Config.
            // Saving them causes duplication or state conflicts on reload.
            if (id === 'HUB' && e.type === 'NPC') return false;
            
            return true;
        })
        .map(e => ({
            type: e.type,
            subType: e.subType,
            x: e.x, y: e.y, z: e.z,
            hp: e.hp,
            state: e.state,
            equipment: e.equipment,
            factionId: e.factionId
        }));
      
      this.sectors.set(id, { entities: snapshot, visited: true, timestamp: Date.now() });
  }

  loadSector(id: SectorId): Entity[] {
      const state = this.sectors.get(id);
      if (!state) return [];
      
      // Rehydrate entities from snapshot
      return state.entities.map(s => {
          const e = { ...s } as Entity;
          e.vx = 0; e.vy = 0; e.angle = 0; e.radius = 20; 
          e.maxHp = s.hp; 
          e.status = { stun: 0, slow: 0, poison: null, burn: null, weakness: null, bleed: null };
          return e;
      });
  }

  reset() { this.sectors.clear(); }
}