
export const RENDER_CONFIG = {
  FRUSTUM_MARGIN: 1000,
  MAX_CACHE_SIZE: 500,
  FLOOR_CACHE_PADDING: 500,
  FLOOR_TILE_SIZE: 200,
  MAX_CANVAS_DIMENSION: 4096,
  Z_SORT_BATCH_SIZE: 100,
  PARTICLE_BATCH_SIZE: 50,
  TARGET_FPS: 60,
  ENABLE_DEBUG_OVERLAY: false,
  ENABLE_PERFORMANCE_MONITORING: true,
  GC_THRESHOLD_MS: 16.67 // 60fps frame budget
};
